### ISSUE TITLE
Running in the browser fails with RangeError

### ISSUE THREAD

**Issue by shamrin** [dyedgreen/deno-sqlite#105] opened 2021-02-20 11:46 UTC
I've followed `deno bundle` manual to get browser of `deno-sqlite`, but it fails in Chrome dev console with `RangeError`:

![image](https://user-images.githubusercontent.com/510678/108594240-72dd1900-7381-11eb-936d-944ef709f17d.png)

```
Uncaught RangeError: WebAssembly.Compile is disallowed on the main thread, if the buffer size is larger than 4KB. Use WebAssembly.compile, or compile on a worker thread.
    at sqlite.bundle.js:215
```

```
$ deno --version
deno 1.7.4 (release, x86_64-apple-darwin)
v8 9.0.123
typescript 4.1.4
$ deno bundle https://deno.land/x/sqlite/mod.ts sqlite.bundle.js
$ cat index.html
<script type="module" src="sqlite.bundle.js"></script>
$ python3 -m http.server 5123
```

(then open http://localhost:5123)

**Comment by dyedgreen** [comment] 2021-02-20 16:11
Thanks for opening the issue @shamrin!

Have you tried to follow the suggestion in the error message (i.e. move the compilation to a worker thread), or does that not suit your use case? (since the SQL queries are run in the WASM context, and they could be rather expensive, it might make sense to run in a worker anyways).

**Comment by shamrin** [comment] 2021-02-20 18:16
@dyedgreen No, I haven't tried it :) I decided to continue using [`sql.js`][1] for now. It does have a [web worker example][2].

I was looking for possible alternatives to `sql.js`. It works fine, but contains uncomfortable amount of [manual memory management from JavaScript][3]. Also, your custom VFS implementation looks very interesting compared to Emscripten MEMFS in sql.js.

What is your view regarding browser support in `deno-sqlite`? I really like how your code is structured. It seems much easier to follow and extend. But it's unclear how open are you in maintaining browser-specific code. The repo is called `deno-sqlite` :-) For example:

* working browser example
* web worker support (or at least an example)
* API to import/export the whole database file
* (maybe) build scripts that don't need `deno`

If I see further problems in sql.js I may consider adding some of the above to `deno-sqlite`, if you are okay with the direction.

[1]: https://github.com/sql-js/sql.js
[2]: https://github.com/sql-js/sql.js/blob/36859494d53f1962f2059d9597782f5f4ab49172/examples/GUI/gui.js#L9
[3]: https://github.com/sql-js/sql.js/blob/master/src/api.js

**Comment by wschenk** [comment] 2021-04-14 18:16
This works if you move it to a webworker, I can confirm.  In memory database operations seem to function fine.  But I'd like to load up a db file, basically load something over a url and then open it.

Is there an option to pass in as a ReadbleStream or something like that?  (I'm not especially familiar with this part of the browser's api so hopefully I'm just being dense.)

**Comment by wschenk** [comment] 2021-04-15 15:05
Example code is here https://willschenk.com/articles/2021/sq_lite_in_the_browser/

**Comment by dyedgreen** [comment] 2021-04-15 15:22
Hm. There is a way to support arbitrary backing storage on web, but it's not super trivial to use.

Basically, you can implement your own [`vfs.js`](https://github.com/dyedgreen/deno-sqlite/blob/master/build/vfs.js) to make things work in the browser. This file contains a few functions that allow SQLite to interact with the file-system. Since you don't have a real file-system in the browser, you could implement something like:
```typescript
interface File {
  buffer: ArrayBuffer;
  size: number; // size of buffer used
}
const files: Map<string, File> = Map();

// implement vfs functions to read/ write to 'files' in the buffers
// (you'll need some sort of strategy for reallocating buffers to grow them on writes)
```

Then you can read/ write to the files before/ after using them with SQLite to load data in or retrieve data for later storage.

Something like this is currently out of scope for the project, since it's more focused towards providing an SQLite library for Deno. But if you come up with a good implementation I'm open to including something like this in the project.

**Comment by dyedgreen** [comment] 2021-05-12 12:47
Closing this for now, since there is no short term plan to officially support browser builds. (This might still change in the future though, so do comment on this issue if there are further comments, questions or suggestions)

**Closed by dyedgreen** 2021-05-12 12:47 UTC
Labels: enhancement

**Comment by dyedgreen** [comment] 2022-01-02 12:43
There is now an experimental branch to support easily building a module that works in browsers (persisting the data in indexedDB, and allowing the import and export of databases).

See #168
