### ISSUE TITLE
error: trailing characters at line 23 column 2 at https://deno.land/x/sqlite@v2.3.1/build/sqlite.js:1:0

### ISSUE THREAD

**Issue by sntg-p** [dyedgreen/deno-sqlite#98] opened 2020-12-13 07:47 UTC
I'm trying to run a project that uses eveningkid/denodb, which in turn uses this library and Deno is throwing this error when trying to cache the dependencies:

> error: trailing characters at line 23 column 2 at https://deno.land/x/sqlite@v2.3.1/build/sqlite.js:1:0

This only seems to be happening in Windows, I've tried Deno 1.4.2 and 1.6.0.

**Comment by dyedgreen** [comment] 2020-12-14 12:58
Thank you for reporting the issue @sntg-p!

This seems like an issue with Deno (you mention windows, have you tried another OS?). Could you provide a minimal working example to reproduce the error (ideally only using SQLite directly, not through `denodb`, so that it becomes easier to track down what causes the issue).

I'd be interested to see if there is something we can do to make it work, or if we should raise this issue with Deno directly 😅 

(this file is a fairly big file, which might be related to the issue, but without a reproducible example it's hard to know)

**Comment by sntg-p** [comment] 2020-12-16 05:19
Just by importing the library in a .ts file

```js
import * as sqlite from "https://deno.land/x/sqlite@v2.3.1/mod.ts";
```

and running that from Deno (tested 1.4.2, 1.6.0 and 1.6.1), it fails with the error in the original post. Tried from the command prompt, PowerShell and bash (mingw), on Windows 10 (1809).

**Comment by dyedgreen** [comment] 2020-12-16 18:40
Hm, I can't seem to repro this with either `v2.3.1` nor `v2.3.2` (on macOS). You said you experienced the issue on Windows, have you tried the same under linux (e.g. using WSL, since you're on Windows)? 😅 

If the issue persists, I think we should raise this in the deno repository directly.

**Comment by jeremyBanks** [comment] 2020-12-17 05:23
I haven't been able to reproduce this.

Tested on Windows 10.0.19041 Pro in PowerShell in Windows Terminal 1.4.3243.0, with the latest two releases of the library (2.3.1, 2.3.2) and with the latest two versions of Deno (1.6.0, 1.6.1). Sample output:

```
PS C:\Users\_> deno --version
deno 1.6.0 (release, x86_64-pc-windows-msvc)
v8 8.8.278.2
typescript 4.1.2

PS C:\Users\_> deno run --reload test.ts
Download https://deno.land/x/sqlite@v2.3.2/mod.ts
Download https://deno.land/x/sqlite@v2.3.1/mod.ts
Download https://deno.land/x/sqlite@v2.3.1/src/constants.ts
Download https://deno.land/x/sqlite@v2.3.1/src/db.ts
Download https://deno.land/x/sqlite@v2.3.1/src/rows.ts
Download https://deno.land/x/sqlite@v2.3.1/build/sqlite.js
Download https://deno.land/x/sqlite@v2.3.1/src/wasm.ts
Download https://deno.land/x/sqlite@v2.3.1/src/error.ts
Download https://deno.land/x/sqlite@v2.3.1/src/row_objects.ts
Download https://deno.land/x/sqlite@v2.3.2/src/rows.ts
Download https://deno.land/x/sqlite@v2.3.2/src/db.ts
Download https://deno.land/x/sqlite@v2.3.2/src/constants.ts
Download https://deno.land/x/sqlite@v2.3.1/build/vfs.js
Download https://deno.land/x/sqlite@v2.3.2/src/wasm.ts
Download https://deno.land/x/sqlite@v2.3.2/src/error.ts
Download https://deno.land/x/sqlite@v2.3.2/src/row_objects.ts
Download https://deno.land/x/sqlite@v2.3.2/build/sqlite.js
Download https://deno.land/x/sqlite@v2.3.2/build/vfs.js
Check file:///C:/Users/_/test.ts
[Function: DB] [Function: DB]

PS C:\Users\_> type test.ts
import * as sqlite1 from "https://deno.land/x/sqlite@v2.3.1/mod.ts";
import * as sqlite2 from "https://deno.land/x/sqlite@v2.3.2/mod.ts";

console.log(sqlite1.DB, sqlite2.DB);
```

**Comment by dyedgreen** [comment] 2020-12-17 09:32
Hm. Could it be a problem with insufficient free storage on your side @sntg-p ? (Seeing that @jeremyBanks cant repro it 😅)

**Comment by sntg-p** [comment] 2020-12-18 22:54
I have almost 24GB left, I don't know what else could I test. :/

**Comment by dyedgreen** [comment] 2021-01-19 18:53
Closing since unable to reproduce 🙁

**Closed by dyedgreen** 2021-01-19 18:53 UTC
Labels: bug, question
